import { copyFile, mkdir, readdir } from "node:fs/promises";
import { join } from "node:path";
import type { HarmonizedGame } from "@pax-pal/core";
import { toSlug } from "@pax-pal/core";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** A discovered game that now has a matching demo-sourced game. */
export interface Promotion {
  /** The old discovered game ID (e.g. "discovered:123:cool-game"). */
  oldId: string;
  /** The new demo-sourced game ID (e.g. "demo:456"). */
  newId: string;
  exhibitorId: string;
  gameName: string;
}

/** A discovered game whose exhibitor now has demos, but no demo matches this game. */
export interface OrphanedDiscovery {
  game: HarmonizedGame;
  /** Why it's orphaned: exhibitor gained demos but none matched this discovered game. */
  reason: string;
}

export interface ReconcileResult {
  /** Demo-sourced games + orphaned discoveries, ready for the discover stage. */
  games: HarmonizedGame[];
  /** Discovered games that were promoted to demo-sourced. */
  promotions: Promotion[];
  /** Discovered games carried forward (exhibitor has demos but no match). */
  orphanedDiscoveries: OrphanedDiscovery[];
  stats: ReconcileStats;
}

export interface ReconcileStats {
  previousDiscoveredGames: number;
  newDemoGames: number;
  promoted: number;
  orphaned: number;
  /** Discovered games whose exhibitor still has no demos (dropped — discover will regenerate). */
  regenerated: number;
  cachesMigrated: number;
}

// ---------------------------------------------------------------------------
// Slug-based matching
// ---------------------------------------------------------------------------

/**
 * Normalize a game name for fuzzy matching.
 * Strips common demo-listing suffixes like "- PAX Demo", "(Demo)", etc.
 */
export function normalizeForMatch(name: string): string {
  return toSlug(
    name
      .replace(/\s*[-–—:]\s*(pax|demo|preview|hands[- ]?on|playable|beta).*$/i, "")
      .replace(/\s*\((pax|demo|preview|hands[- ]?on|playable|beta)[^)]*\)/i, "")
      .trim(),
  );
}

/**
 * Check if two game names match, accounting for demo-listing name variations.
 * Returns true for exact slug match or normalized match.
 */
export function namesMatch(discoveredName: string, demoName: string): boolean {
  // Exact slug match
  if (toSlug(discoveredName) === toSlug(demoName)) return true;

  // Normalized match (strips demo suffixes)
  const normDiscovered = normalizeForMatch(discoveredName);
  const normDemo = normalizeForMatch(demoName);
  if (normDiscovered === normDemo) return true;

  // Check if one is a prefix of the other (handles "Cool Game" vs "Cool Game 2: Reloaded" — no match,
  // but "Cool Game" vs "Cool Game - Demo Edition" — match via normalization above)
  return false;
}

// ---------------------------------------------------------------------------
// Core reconciliation
// ---------------------------------------------------------------------------

/**
 * Reconcile previous pipeline state with freshly harmonized data.
 *
 * Identifies discovered games that now have demo-sourced equivalents (promotions),
 * discovered games that should be carried forward (orphans), and discovered games
 * that will be regenerated by the discover stage.
 */
export function reconcile(
  freshDemoGames: HarmonizedGame[],
  previousGames: HarmonizedGame[],
): Omit<ReconcileResult, "stats"> & { stats: Omit<ReconcileStats, "cachesMigrated"> } {
  // Separate previous games into demo-sourced and discovered
  const previousDiscovered = previousGames.filter(
    (g) => g.demoId === null && g.discoverySource !== null,
  );

  // Group fresh demo games by exhibitorId
  const demosByExhibitor = new Map<string, HarmonizedGame[]>();
  for (const game of freshDemoGames) {
    const group = demosByExhibitor.get(game.exhibitorId);
    if (group) {
      group.push(game);
    } else {
      demosByExhibitor.set(game.exhibitorId, [game]);
    }
  }

  const promotions: Promotion[] = [];
  const orphanedDiscoveries: OrphanedDiscovery[] = [];
  let regenerated = 0;

  for (const discovered of previousDiscovered) {
    const exhibitorDemos = demosByExhibitor.get(discovered.exhibitorId);

    if (!exhibitorDemos) {
      // Exhibitor still has no demos — discover will regenerate this game (cached)
      regenerated++;
      continue;
    }

    // Try to match this discovered game to a demo
    const match = exhibitorDemos.find((demo) => namesMatch(discovered.name, demo.name));

    if (match) {
      promotions.push({
        oldId: discovered.id,
        newId: match.id,
        exhibitorId: discovered.exhibitorId,
        gameName: discovered.name,
      });
    } else {
      // Exhibitor has demos but none match this discovered game — carry it forward
      orphanedDiscoveries.push({
        game: discovered,
        reason: `Exhibitor now has ${exhibitorDemos.length} demo(s) but none match "${discovered.name}"`,
      });
    }
  }

  // Build output: fresh demo games + orphaned discoveries
  const games = [...freshDemoGames, ...orphanedDiscoveries.map((o) => o.game)];

  return {
    games,
    promotions,
    orphanedDiscoveries,
    stats: {
      previousDiscoveredGames: previousDiscovered.length,
      newDemoGames: freshDemoGames.length,
      promoted: promotions.length,
      orphaned: orphanedDiscoveries.length,
      regenerated,
    },
  };
}

// ---------------------------------------------------------------------------
// Cache migration
// ---------------------------------------------------------------------------

/**
 * Copy enrich cache files from old game IDs to new game IDs for promoted games.
 * Handles bgg, web, and steam cache directories.
 */
export async function migrateEnrichCaches(
  promotions: Promotion[],
  enrichCacheDirs: { bgg?: string; web?: string; steam?: string },
): Promise<number> {
  if (promotions.length === 0) return 0;

  let migrated = 0;
  const dirs = [enrichCacheDirs.bgg, enrichCacheDirs.web, enrichCacheDirs.steam].filter(
    (d): d is string => d != null,
  );

  for (const dir of dirs) {
    let existingFiles: Set<string>;
    try {
      existingFiles = new Set(await readdir(dir));
    } catch {
      continue; // Cache dir doesn't exist yet
    }

    for (const { oldId, newId } of promotions) {
      const oldFile = `${oldId}.json`;
      const newFile = `${newId}.json`;

      if (existingFiles.has(oldFile) && !existingFiles.has(newFile)) {
        await mkdir(dir, { recursive: true });
        await copyFile(join(dir, oldFile), join(dir, newFile));
        migrated++;
      }
    }
  }

  return migrated;
}

// ---------------------------------------------------------------------------
// Full reconciliation with cache migration
// ---------------------------------------------------------------------------

export interface ReconcileOptions {
  enrichCacheDirs?: { bgg?: string; web?: string; steam?: string };
}

/**
 * Run reconciliation and migrate enrich caches in one call.
 */
export async function reconcileWithCaches(
  freshDemoGames: HarmonizedGame[],
  previousGames: HarmonizedGame[],
  options: ReconcileOptions = {},
): Promise<ReconcileResult> {
  const result = reconcile(freshDemoGames, previousGames);

  let cachesMigrated = 0;
  if (options.enrichCacheDirs && result.promotions.length > 0) {
    cachesMigrated = await migrateEnrichCaches(result.promotions, options.enrichCacheDirs);
  }

  return {
    ...result,
    stats: { ...result.stats, cachesMigrated },
  };
}
